package org.jhipster.student.enrolment.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StudentIdCardAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentIdCardAllPropertiesEquals(StudentIdCard expected, StudentIdCard actual) {
        assertStudentIdCardAutoGeneratedPropertiesEquals(expected, actual);
        assertStudentIdCardAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentIdCardAllUpdatablePropertiesEquals(StudentIdCard expected, StudentIdCard actual) {
        assertStudentIdCardUpdatableFieldsEquals(expected, actual);
        assertStudentIdCardUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentIdCardAutoGeneratedPropertiesEquals(StudentIdCard expected, StudentIdCard actual) {
        assertThat(expected)
            .as("Verify StudentIdCard auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentIdCardUpdatableFieldsEquals(StudentIdCard expected, StudentIdCard actual) {
        assertThat(expected)
            .as("Verify StudentIdCard relevant properties")
            .satisfies(e -> assertThat(e.getCardNumber()).as("check cardNumber").isEqualTo(actual.getCardNumber()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentIdCardUpdatableRelationshipsEquals(StudentIdCard expected, StudentIdCard actual) {
        // empty method
    }
}
